from youtube_transcript_api import YouTubeTranscriptApi


def is_valid_video_id(video_id):
    try:
        langs = YouTubeTranscriptApi.list_transcripts(video_id)
        print(langs)
        manual_langs = list(langs._manually_created_transcripts.keys())
        generated_langs = list(langs._generated_transcripts.keys())
        # always prefer manual lang over autogenerated one
        generated_langs = [lang for lang in generated_langs if lang not in manual_langs]
        final_langs = manual_langs + generated_langs
        if len(final_langs) == 0:
            return "Video has no captions available"
        return final_langs
    except Exception as e:  # it would have been better if YTApi had made custom error objects
        print(e)
        if "VideoUnavailable" in str(type(e)):
            return "Video unvailable: check link again"